# Generated by Django 5.2 on 2026-06-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_lgpd'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sol_tour_shown',
            field=models.BooleanField(default=False),
        ),
    ]
