# Generated by Django 5.2 on 2026-05-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_recurringtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
