# Generated by Django 5.2 on 2026-05-27 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_userachievement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_investment',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('buy', 'Compra'), ('sell', 'Venda'), ('earnings', 'Rendimento')], max_length=10)),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inv_transactions', to='finances.account')),
                ('cash_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inv_boleta', to='finances.transaction')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas', to='finances.investment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boleta de Investimento',
                'verbose_name_plural': 'Boletas de Investimento',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
